services:
  - type: web
    name: kaikai-main
    env: docker
    plan: free
    dockerCommand: docker-compose up --build
    containerPort: 80
    envVars:
      - key: POSTGRES_URL
        fromDatabase:
          name: kaikaidb
          property: connectionString

databases:
  - name: kaikaidb
    plan: free
    databaseName: kaishield_db
    user: kaishield_user
