name: Render Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Render Login
        uses: render-actions/login@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}

      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          wait: true
